# -*- coding: utf-8 -*-
"""comparacion_ensembles.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyZLTq9DRC6DLkN2vNZ0h1Iwq4Vdlac8
"""

# ============================
# Comparación Regresión Logística vs Ensemble
# Complicaciones postoperatorias (dataset simulado)
# ============================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

# ----------------------------
# 1. Simulación del dataset
# ----------------------------
np.random.seed(42)
n_pacientes = 300

Edad = np.random.randint(18, 90, size=n_pacientes)
Comorbilidades_Indice = np.random.randint(0, 11, size=n_pacientes)  # 0-10
Tipo_Cirugia = np.random.choice([1, 2, 3], size=n_pacientes, p=[0.4, 0.35, 0.25])  # 1=Menor, 2=Media, 3=Mayor
Estancia_Previa = np.random.poisson(3, size=n_pacientes)  # días de espera

# Generamos una probabilidad de complicación NO lineal
# - mayor riesgo en cirugías mayores
# - interacción suave entre Edad y cirugía mayor
logit = (
    -4
    + 0.02 * Edad
    + 0.18 * Comorbilidades_Indice
    + 0.12 * Estancia_Previa
    + np.where(Tipo_Cirugia == 2, 0.7, 0)
    + np.where(Tipo_Cirugia == 3, 1.2, 0)
    + 0.015 * Edad * (Tipo_Cirugia == 3)
)

prob_comp = 1 / (1 + np.exp(-logit))
Complicacion = np.random.binomial(1, prob_comp)

df = pd.DataFrame({
    "Edad": Edad,
    "Comorbilidades_Indice": Comorbilidades_Indice,
    "Tipo_Cirugia": Tipo_Cirugia,
    "Estancia_Previa": Estancia_Previa,
    "Complicacion": Complicacion
})

print("Prevalencia de complicaciones:", df["Complicacion"].mean().round(3))
print(df.head())

# ----------------------------
# 2. One-Hot Encoding y Train/Test
# ----------------------------
X = df.drop(columns=["Complicacion"])
y = df["Complicacion"]

# One-Hot Encoding para Tipo_Cirugia
X_encoded = pd.get_dummies(X, columns=["Tipo_Cirugia"], drop_first=True)
print("\nColumnas después de One-Hot Encoding:")
print(X_encoded.columns)

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.3, random_state=42, stratify=y
)

print("\nTamaño entrenamiento:", X_train.shape[0])
print("Tamaño prueba:", X_test.shape[0])

# ----------------------------
# 3A. Árbol de decisión (max_depth=3)
# ----------------------------
tree_model = DecisionTreeClassifier(max_depth=3, random_state=42)
tree_model.fit(X_train, y_train)

y_proba_tree = tree_model.predict_proba(X_test)[:, 1]
auc_tree = roc_auc_score(y_test, y_proba_tree)
print(f"\nAUC Árbol de Decisión (Test): {auc_tree:.3f}")

# Visualización y guardado del árbol
plt.figure(figsize=(14, 8))
plot_tree(
    tree_model,
    feature_names=X_encoded.columns,
    class_names=["No Complicación", "Complicación"],
    filled=True,
    rounded=True,
    proportion=True,
    fontsize=10
)
plt.title("Árbol de Decisión - Complicaciones Postoperatorias")
plt.savefig("arbol_decision.png", dpi=300, bbox_inches="tight")
plt.close()

print("Se guardó el archivo: arbol_decision.png")

# ----------------------------
# 3B. Regresión Logística
# ----------------------------
log_model = LogisticRegression(max_iter=1000, random_state=42)
log_model.fit(X_train, y_train)

y_proba_log = log_model.predict_proba(X_test)[:, 1]
auc_log = roc_auc_score(y_test, y_proba_log)
print(f"AUC Regresión Logística (Test): {auc_log:.3f}")

# ----------------------------
# 3C. Modelo de Ensamblaje: Random Forest
# ----------------------------
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
rf_model.fit(X_train, y_train)

y_proba_rf = rf_model.predict_proba(X_test)[:, 1]
auc_rf = roc_auc_score(y_test, y_proba_rf)
print(f"AUC Random Forest (Test): {auc_rf:.3f}")

# ----------------------------
# 3D. Importancia de atributos (Random Forest)
# ----------------------------
importances = rf_model.feature_importances_
features = X_encoded.columns

imp_df = pd.DataFrame({
    "feature": features,
    "importance": importances
}).sort_values("importance", ascending=False)

print("\nImportancia de atributos (Random Forest):")
print(imp_df)

plt.figure(figsize=(8, 5))
plt.barh(imp_df["feature"], imp_df["importance"])
plt.gca().invert_yaxis()
plt.xlabel("Importancia")
plt.title("Importancia de Atributos - Random Forest")
plt.savefig("importancia_atributos.png", dpi=300, bbox_inches="tight")
plt.close()

print("Se guardó el archivo: importancia_atributos.png")

# Resumen final en consola
print("\n--- Resumen de AUC en Test ---")
print(f"Árbol       : {auc_tree:.3f}")
print(f"Logística   : {auc_log:.3f}")
print(f"RandomForest: {auc_rf:.3f}")